#!/usr/bin/env python3
"""
Example script demonstrating how to use export_to_projector()

This script shows how to:
1. Create sample embeddings and data
2. Export to Google Embedding Projector format
3. Verify the output files

Usage:
    python example_export_usage.py
"""

import numpy as np
import pandas as pd
import os

# Import the export function
from nlp import export_to_projector

def create_sample_data():
    """Create sample embeddings and dataframe for demonstration"""
    print("Creating sample data...")
    
    # Simulate 384-dimensional embeddings (as generated by paraphrase-multilingual-MiniLM-L12-v2)
    n_samples = 20
    n_dimensions = 384
    
    # Generate random normalized embeddings
    embeddings = np.random.randn(n_samples, n_dimensions)
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    embeddings = embeddings / norms
    
    # Create sample dataframe with multilingual texts
    sample_texts = [
        # English samples
        "This game has amazing graphics and smooth gameplay!",
        "The storyline is engaging but controls could be better",
        "Great sound design and immersive atmosphere",
        "Character development is top-notch",
        "Could use more variety in missions",
        
        # Chinese samples
        "这个游戏的画面非常精美",
        "剧情很吸引人但是操作有点复杂",
        "音效设计很棒，氛围感十足",
        "角色设计很有特色",
        "任务种类可以更丰富一些",
        
        # Japanese samples
        "このゲームのグラフィックは素晴らしい",
        "ストーリーは面白いが操作が難しい",
        "サウンドデザインが素晴らしい",
        "キャラクターの成長が楽しい",
        "もっとミッションの種類が欲しい",
        
        # Mixed samples
        "Overall great game but needs optimization",
        "价格合理，内容丰富",
        "コストパフォーマンスが良い",
        "Highly recommended for RPG fans",
        "总体来说是一款优秀的游戏"
    ]
    
    df = pd.DataFrame({
        'text': sample_texts,
        'topic_id': [1, 2, 3, 4, 2, 1, 2, 3, 4, 2, 1, 2, 3, 4, 2, 5, 5, 5, 5, 5],
        'sentiment': np.random.randn(n_samples) * 0.3
    })
    
    print(f"✓ Created {n_samples} samples with {n_dimensions} dimensions")
    return embeddings, df

def demonstrate_basic_export():
    """Demonstrate basic export functionality"""
    print("\n" + "="*70)
    print("EXAMPLE 1: Basic Export")
    print("="*70)
    
    embeddings, df = create_sample_data()
    
    # Export to default location
    result = export_to_projector(embeddings, df, output_dir='.')
    
    print("\nExport completed!")
    print(f"  Vectors file: {result['vectors_path']}")
    print(f"  Metadata file: {result['metadata_path']}")
    print(f"  Number of samples: {result['num_samples']}")
    print(f"  Dimensions: {result['dimensions']}")
    print(f"  Language distribution: {result['languages']}")
    
    return result

def demonstrate_custom_export():
    """Demonstrate export with custom settings"""
    print("\n" + "="*70)
    print("EXAMPLE 2: Custom Output Directory")
    print("="*70)
    
    embeddings, df = create_sample_data()
    
    # Create custom output directory
    output_dir = './projector_visualization'
    os.makedirs(output_dir, exist_ok=True)
    
    # Export with custom filenames
    result = export_to_projector(
        embeddings=embeddings,
        dataframe=df,
        output_dir=output_dir,
        vectors_filename='game_embeddings.tsv',
        metadata_filename='game_metadata.tsv'
    )
    
    print("\nExport completed!")
    print(f"  Vectors file: {result['vectors_path']}")
    print(f"  Metadata file: {result['metadata_path']}")
    
    return result

def demonstrate_filtered_export():
    """Demonstrate exporting filtered data"""
    print("\n" + "="*70)
    print("EXAMPLE 3: Exporting Filtered Topics")
    print("="*70)
    
    embeddings, df = create_sample_data()
    
    # Filter to only topics 1, 2, and 3
    selected_topics = [1, 2, 3]
    mask = df['topic_id'].isin(selected_topics)
    
    filtered_df = df[mask].reset_index(drop=True)
    filtered_embeddings = embeddings[mask]
    
    print(f"Original samples: {len(df)}")
    print(f"Filtered samples: {len(filtered_df)}")
    print(f"Selected topics: {selected_topics}")
    
    # Export filtered data
    result = export_to_projector(
        filtered_embeddings, 
        filtered_df, 
        output_dir='.',
        vectors_filename='filtered_vectors.tsv',
        metadata_filename='filtered_metadata.tsv'
    )
    
    print("\nFiltered export completed!")
    print(f"  Exported {result['num_samples']} samples")
    
    return result

def verify_output_files(result):
    """Verify that output files are correctly formatted"""
    print("\n" + "="*70)
    print("VERIFICATION: Output File Format")
    print("="*70)
    
    # Check vectors file
    print("\nChecking vectors.tsv...")
    with open(result['vectors_path'], 'r') as f:
        lines = f.readlines()
        print(f"  ✓ Number of rows: {len(lines)}")
        
        first_line = lines[0].strip().split('\t')
        print(f"  ✓ Dimensions per row: {len(first_line)}")
        print(f"  ✓ Sample values: {first_line[:3]}...")
    
    # Check metadata file
    print("\nChecking metadata.tsv...")
    metadata_df = pd.read_csv(result['metadata_path'], sep='\t')
    print(f"  ✓ Number of rows: {len(metadata_df)}")
    print(f"  ✓ Columns: {list(metadata_df.columns)}")
    
    print("\n  Sample rows:")
    for i, row in metadata_df.head(3).iterrows():
        print(f"    Row {i}: {row['language']:8s} | Topic {row['topic_id']} | {row['text'][:40]}...")
    
    # Verify no special characters in metadata
    print("\n  Checking for special characters...")
    has_tabs = metadata_df['text'].str.contains('\t').any()
    has_newlines = metadata_df['text'].str.contains('\n').any()
    
    if not has_tabs and not has_newlines:
        print("  ✓ No tabs or newlines in text (TSV format preserved)")
    else:
        print("  ✗ Warning: Found special characters that may break TSV format")

def print_usage_instructions():
    """Print instructions for using with Google Embedding Projector"""
    print("\n" + "="*70)
    print("HOW TO USE WITH GOOGLE EMBEDDING PROJECTOR")
    print("="*70)
    print("""
1. Go to: https://projector.tensorflow.org/

2. Click the "Load" button in the left sidebar

3. Under "Load data":
   - Click "Choose file" next to "Load a TSV file of vectors"
   - Select the vectors.tsv file (or game_embeddings.tsv)
   
4. Under "Load a TSV file of metadata":
   - Click "Choose file"
   - Select the metadata.tsv file (or game_metadata.tsv)

5. The projector will automatically link them!

6. Explore your data:
   - Color by "language" to see Chinese/Japanese/English clusters
   - Color by "topic_id" to see topic clusters
   - Try different algorithms (PCA, t-SNE, UMAP)
   - Search for specific text to find similar comments
   - Click points to see their metadata

7. Tips:
   - t-SNE works best for local structure (clusters)
   - UMAP is a good balance
   - PCA is fastest but less detailed
   - Adjust perplexity/neighbors for t-SNE/UMAP
""")

def main():
    """Run all examples"""
    print("\n" + "="*70)
    print("GOOGLE EMBEDDING PROJECTOR EXPORT - USAGE EXAMPLES")
    print("="*70)
    print("\nThis script demonstrates how to use the export_to_projector() function")
    print("to prepare embeddings for visualization in Google's Embedding Projector.\n")
    
    try:
        # Example 1: Basic export
        result1 = demonstrate_basic_export()
        
        # Example 2: Custom output
        result2 = demonstrate_custom_export()
        
        # Example 3: Filtered export
        result3 = demonstrate_filtered_export()
        
        # Verify the output
        verify_output_files(result1)
        
        # Print usage instructions
        print_usage_instructions()
        
        print("\n" + "="*70)
        print("✅ ALL EXAMPLES COMPLETED SUCCESSFULLY")
        print("="*70)
        print("\nGenerated files:")
        print(f"  - vectors.tsv")
        print(f"  - metadata.tsv")
        print(f"  - filtered_vectors.tsv")
        print(f"  - filtered_metadata.tsv")
        print(f"  - projector_visualization/game_embeddings.tsv")
        print(f"  - projector_visualization/game_metadata.tsv")
        print("\nYou can now upload these files to https://projector.tensorflow.org/")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Error occurred: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    import sys
    sys.exit(main())
